### ISSUE TITLE
ZRTP failed both the masterKey length and saltKey length check in jitsi-srtp-1.0-SNAPSHOT implementation

### ISSUE THREAD

**Issue by cmeng-git** [jitsi/zrtp4j#5]
The SrtpContextFactory.java class in the latest jitsi-srtp-1.0-SNAPSHOT library implementation now includes check for both the masterKey length and saltKey length against the values specified in SrtpPolicy (or ZrtpConstants). It is found that the key length generated in ZRtp KDF is always 16-bytes longer than the SrtpPolicy specified values. The problem happens for both the zrtp4j-light-4.1.1.jar and zrtp4j-light-4.1.0.jar releases.

It has been verified that both the SDES and DTLS-SRTP implementation work with the jitsi-srtp-1.0-SNAPSHOT implementation. Below is the debug log captured on aTalk. The test was carried out between aTalk and Jitsi (Ubuntu) 2.11.5611.
Similar problem also happen for jitsi compiled with the latest source from the master github repository. 

```
2020-07-05 09:00:25.453 17568-18308/org.atalk.android D/SMACK: RECV (0): 
    <iq xml:lang='en' to='swordfish@atalk.sytes.net/atalk' from='kingfisher@atalk.sytes.net/jitsi-q0l50n' type='result' id='CXNK2-26'/>

2020-07-05 09:00:27.187 17568-18786/org.atalk.android W/(SecurityEventManager.java:253)#showMessage: AUDIO_SESSION: ZRTP message (Info): code: InfoHelloReceived; message: null
2020-07-05 09:00:27.202 17568-18786/org.atalk.android W/(SecurityEventManager.java:253)#showMessage: AUDIO_SESSION: ZRTP message (Info): code: InfoCommitDHGenerated; message: null
2020-07-05 09:00:27.662 17568-18786/org.atalk.android W/(SecurityEventManager.java:253)#showMessage: AUDIO_SESSION: ZRTP message (Info): code: InfoInitDH1Received; message: null
2020-07-05 09:00:27.673 17568-18786/org.atalk.android W/(SecurityEventManager.java:253)#showMessage: AUDIO_SESSION: ZRTP message (Info): code: InfoRSMatchFound; message: null
2020-07-05 09:00:27.674 17568-18786/org.atalk.android D/(ZRtp.java:2772)#KDF: Length: 128; HashLength: 32
2020-07-05 09:00:27.675 17568-18786/org.atalk.android D/(ZRtp.java:2772)#KDF: Length: 112; HashLength: 32
2020-07-05 09:00:27.676 17568-18786/org.atalk.android D/(ZRtp.java:2772)#KDF: Length: 128; HashLength: 32
2020-07-05 09:00:27.677 17568-18786/org.atalk.android W/(ZRtp.java:2801)#computeSRTPKeys: Srtp Response Key: 32 (128) = [B@830e4fd
2020-07-05 09:00:27.678 17568-18786/org.atalk.android D/(ZRtp.java:2772)#KDF: Length: 112; HashLength: 32
2020-07-05 09:00:27.679 17568-18786/org.atalk.android D/(ZRtp.java:2772)#KDF: Length: 256; HashLength: 32
2020-07-05 09:00:27.679 17568-18786/org.atalk.android D/(ZRtp.java:2772)#KDF: Length: 256; HashLength: 32
2020-07-05 09:00:27.680 17568-18786/org.atalk.android D/(ZRtp.java:2772)#KDF: Length: 128; HashLength: 32
2020-07-05 09:00:27.680 17568-18786/org.atalk.android D/(ZRtp.java:2772)#KDF: Length: 128; HashLength: 32
2020-07-05 09:00:27.681 17568-18786/org.atalk.android D/(ZRtp.java:2772)#KDF: Length: 256; HashLength: 32
2020-07-05 09:00:27.682 17568-18786/org.atalk.android D/(ZRtp.java:2772)#KDF: Length: 256; HashLength: 32
2020-07-05 09:00:27.775 17568-18786/org.atalk.android W/(SecurityEventManager.java:253)#showMessage: AUDIO_SESSION: ZRTP message (Info): code: InfoInitConf1Received; message: null
2020-07-05 09:00:27.788 17568-18786/org.atalk.android D/(SecurityEventManager.java:130)#secureOn: AUDIO_SESSION: cipher enabled: AES-CM-128/DH3K
2020-07-05 09:00:27.789 17568-18786/org.atalk.android D/(SecurityEventManager.java:143)#showSAS: AUDIO_SESSION: SAS is: 1wr7
2020-07-05 09:00:27.795 17568-18786/org.atalk.android E/(SinglePacketTransformer.java:216)#transformArray: Failed to reverseTransform RawPacket(s)!
    java.lang.IllegalArgumentException: masterK.length != encKeyLength (32 : 16)
        at org.atalk.impl.neomedia.transform.srtp.SrtpContextFactory.<init>(SrtpContextFactory.java:74)
        at org.atalk.impl.neomedia.transform.zrtp.ZRTPTransformEngine.srtpSecretsReady(ZRTPTransformEngine.java:818)
        at gnu.java.zrtp.ZRtp.srtpSecretsReady(ZRtp.java:2481)
        at gnu.java.zrtp.ZrtpStateClass.evWaitConfirm1(ZrtpStateClass.java:1316)
        at gnu.java.zrtp.ZrtpStateClass.dispatchEvent(ZrtpStateClass.java:335)
        at gnu.java.zrtp.ZrtpStateClass.processEvent(ZrtpStateClass.java:287)
        at gnu.java.zrtp.ZRtp.processZrtpMessage(ZRtp.java:561)
        at org.atalk.impl.neomedia.transform.zrtp.ZRTPTransformEngine.reverseTransform(ZRTPTransformEngine.java:699)
        at org.atalk.impl.neomedia.transform.-$$Lambda$KpqTOGim0FGCQHqRXPZjVA7awAk.apply(Unknown Source:4)
        at org.atalk.impl.neomedia.transform.SinglePacketTransformer.transformArray(SinglePacketTransformer.java:211)
        at org.atalk.impl.neomedia.transform.SinglePacketTransformer.reverseTransform(SinglePacketTransformer.java:121)
        at org.atalk.impl.neomedia.transform.TransformEngineChain$PacketTransformerChain.reverseTransform(TransformEngineChain.java:328)
        at org.atalk.impl.neomedia.transform.TransformInputStream.createRawPacket(TransformInputStream.java:63)
        at org.atalk.impl.neomedia.RTPConnectorInputStream.runInReceiveThread(RTPConnectorInputStream.java:592)
        at org.atalk.impl.neomedia.RTPConnectorInputStream.access$000(RTPConnectorInputStream.java:37)
        at org.atalk.impl.neomedia.RTPConnectorInputStream$2.run(RTPConnectorInputStream.java:429)
```

**Comment by cmeng-git** [comment]
Need the following changes in ZRTPTransformEngine#srtpSecretsReady() to fix the problem.

```
============ ZRTPTransformEngine ============
    /**
     * Switch on the security for the defined part.
     * 4.5.1.  The ZRTP Key Derivation Function
     * The output of the KDF is truncated to the leftmost L bits
     * 4.5.3.  Deriving the Rest of the Keys from s0
     * ... AES-CM 128 or 256-bit key length, 112-bit session salt key length...
     * (Need to performed here as it is not done in ZRtp class.
     *
     * @param secrets The secret keys and salt negotiated by ZRTP.
     * @param part An enum that defines sender, receiver, or both.
     * @return always return true.
     */
    public boolean srtpSecretsReady(ZrtpSrtpSecrets secrets, EnableSecurity part)
    {
        SrtpPolicy srtpPolicy;
        int cipher = 0, authn = 0, authKeyLen = 0;

        if (secrets.getAuthAlgorithm() == ZrtpConstants.SupportedAuthAlgos.HS) {
            authn = SrtpPolicy.HMACSHA1_AUTHENTICATION;
            authKeyLen = 20;
        }
        else if (secrets.getAuthAlgorithm() == ZrtpConstants.SupportedAuthAlgos.SK) {
            authn = SrtpPolicy.SKEIN_AUTHENTICATION;
            authKeyLen = 32;
        }

        if (secrets.getSymEncAlgorithm() == ZrtpConstants.SupportedSymAlgos.AES) {
            cipher = SrtpPolicy.AESCM_ENCRYPTION;
        }
        else if (secrets.getSymEncAlgorithm() == ZrtpConstants.SupportedSymAlgos.TwoFish) {
            cipher = SrtpPolicy.TWOFISH_ENCRYPTION;
        }

        // Actually both Initiator and Responder have the same  masterKey and saltKey Length
        int srtp_auth_tag_length = secrets.getSrtpAuthTagLen() / 8;
        int initiator_cipher_key_length =  secrets.getInitKeyLen() / 8;
        int initiator_cipher_salt_length =  secrets.getInitSaltLen() / 8;
        int responder_cipher_key_length =  secrets.getRespKeyLen() / 8;
        int responder_cipher_salt_length =  secrets.getRespSaltLen() / 8;

        byte[] initiator_SRTP_master_key = new byte[initiator_cipher_key_length];
        byte[] initiator_SRTP_master_salt = new byte[initiator_cipher_salt_length];
        byte[] responder_SRTP_master_key = new byte[responder_cipher_key_length];
        byte[] responder_SRTP_master_salt = new byte[responder_cipher_salt_length];

        System.arraycopy(secrets.getKeyInitiator(), 0,
                initiator_SRTP_master_key, 0, initiator_cipher_key_length);
        System.arraycopy(secrets.getSaltInitiator(), 0,
                initiator_SRTP_master_salt, 0, initiator_cipher_salt_length);
        System.arraycopy(secrets.getKeyResponder(), 0,
                responder_SRTP_master_key, 0, responder_cipher_key_length);
        System.arraycopy(secrets.getSaltResponder(), 0,
                responder_SRTP_master_salt, 0, responder_cipher_salt_length);

        if (part == EnableSecurity.ForSender) {
            // To encrypt packets: initiator uses initiator keys, responder uses responder keys
            // Create a "half baked" crypto context first and store it. This is
            // the main crypto context for the sending part of the connection.
            if (secrets.getRole() == Role.Initiator) {
                srtpPolicy = new SrtpPolicy(cipher,
                        initiator_cipher_key_length,
                        authn, authKeyLen,
                        srtp_auth_tag_length,
                        initiator_cipher_salt_length
                );

                SrtpContextFactory engine = new SrtpContextFactory(
                        true,
                        initiator_SRTP_master_key,
                        initiator_SRTP_master_salt,
                        srtpPolicy, srtpPolicy);

                srtpOutTransformer = new SRTPTransformer(engine);
                getRTCPTransformer().setSrtcpOut(new SRTCPTransformer(engine));
            }
            else {
                srtpPolicy = new SrtpPolicy(
                        cipher,
                        responder_cipher_key_length,
                        authn, authKeyLen,
                        srtp_auth_tag_length,
                        responder_cipher_salt_length
                );

                SrtpContextFactory engine = new SrtpContextFactory(
                        true,
                        responder_SRTP_master_key,
                        responder_SRTP_master_salt,
                        srtpPolicy, srtpPolicy);

                srtpOutTransformer = new SRTPTransformer(engine);
                getRTCPTransformer().setSrtcpOut(new SRTCPTransformer(engine));
            }
        }
        else if (part == EnableSecurity.ForReceiver) {
            // To decrypt packets: initiator uses responder keys, responder initiator keys
            // See comment above.
            if (secrets.getRole() == Role.Initiator) {
                srtpPolicy = new SrtpPolicy(
                        cipher,
                        responder_cipher_key_length,
                        authn, authKeyLen,
                        srtp_auth_tag_length,
                        responder_cipher_salt_length
                );

                SrtpContextFactory engine = new SrtpContextFactory(
                        false /* receiver */,
                        responder_SRTP_master_key,
                        responder_SRTP_master_salt,
                        srtpPolicy, srtpPolicy);

                srtpInTransformer = new SRTPTransformer(engine);
                getRTCPTransformer().setSrtcpIn(new SRTCPTransformer(engine));
                this.muted = false;
            }
            else {
                srtpPolicy = new SrtpPolicy(
                        cipher,
                        initiator_cipher_key_length,
                        authn, authKeyLen,
                        srtp_auth_tag_length,
                        initiator_cipher_salt_length
                );

                SrtpContextFactory engine = new SrtpContextFactory(
                        false /* receiver */,
                        initiator_SRTP_master_key,
                        initiator_SRTP_master_salt,
                        srtpPolicy, srtpPolicy);

                srtpInTransformer = new SRTPTransformer(engine);
                getRTCPTransformer().setSrtcpIn(new SRTCPTransformer(engine));
                this.muted = false;
            }
        }
        return true;
    }
```
